// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orecrgcfrlpivjgxjnln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yZWNyZ2NmcmxwaXZqZ3hqbmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2OTgwMjUsImV4cCI6MjA1NzI3NDAyNX0.sqakPUf9NnO532FJsABpf05tB1wwlMRRARBoBjKghpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});